### ISSUE TITLE
Integrated search engine

### ISSUE THREAD

**Issue by amirouche** [openzim/sotoki#1]
I think it will be better to have a search engine integrated to the static version of the website. The problem is that the index is too big to be built by the user even for superuser (20MB). [lunrjs](http://lunrjs.com/docs/) provide numerous entry points. Here is the solutions that remains to be explored:
- build the index using lunr and store in the build directory. Load the index from the build directory.
- If the above doesn't work because the index is too big (and it might be too big for slow machines). Create a new index for lunr.js that fetch store items lazily as required by the query engine this will save a lot of memory.

I think it's better to contribute back to lunr.js which is an established project regarding this topic. I had a look a look at other solutions but they more complicated and we only require english support.

Maybe it's better to thing I18N and go with a FTS solution that can handle mutliple languages. Again, I think it's better to have search integrated to the static part of the ZIM file that have search engine built inside the kiwix reader which breaks UX.

**Comment by kelson42** [comment]
Did you have had a look to the solution used for Gutenberg? I would recommend to get the static pages done and correctly linked. Make a first version and then work on this. Meanwhile the reader fulltext search engine should do the job.

**Comment by amirouche** [comment]
This is kind of complex. I'd like to do a first release before working on that.

**Comment by dattaz** [comment]
As discuss with @kelson42 search in zimlib, will, for the moment and for the use case, be enough
