### ISSUE TITLE
Remove resize_image_profile and use download_image

### ISSUE THREAD

**Issue by dattaz** [openzim/sotoki#109]
Remplace https://github.com/openzim/sotoki/blob/master/sotoki/sotoki.py#L995:L996 with call to `download_image`

and remove https://github.com/openzim/sotoki/blob/master/sotoki/sotoki.py#L1000:L1005

**Comment by satyamtg** [comment]
Hey @dattaz did a quick fix. Have a look here https://github.com/openzim/sotoki/pull/118
