### ISSUE TITLE
Simplify pre-processing process

### ISSUE THREAD

**Issue by dattaz** [openzim/sotoki#110]
Since we use SAX driver for parsing XML, we reformate and interweave XML dump before processing.
This is done using UNIX tools like sed, sort and some custom python script. See `prepare_xml.sh`.

We may need to simplify this process because it takes a significant part of the process (depend of dump but up to 30% of preparation+html generation)

**Comment by kelson42** [comment]
@dattaz Do you thin a pure Python SAX parsing is the solution? Would you be able to make it?

**Comment by dattaz** [comment]
The main issue here is : We have many XML (one for comments, one for post, one for links beetween post, one for user, one for tag + one for user with one for badges)  which have link between them, and we want to parse them all to generate page. 

The idea at the time was to not use any "database"-like to get information and read XML only once (and in a lazy way, without DOM tree (too much data))

The solution was to merge and interleave all XML file (except user and tag) to one "big" XML. For each post, we put comment which are respond to this post just after in the file as exemple. With this solution we have all information when we read XML with SAX parser (each post have information about his answers, comment, links)

Preparation use :
- `sed` : To remove root balise of XML, get list of post title with id and make file 2 file one for post, one for answers for Posts.xml (which will be merge after in the right place inside "big" XML)
- `sort` : To sort file (which is important to interleave => ~ if id from file 1 < id from file 2, write line from file 1)
- Custom python file for interleave (and add XML tags between) (since i've not found any UNIX tools to do it).   


I think the idea behind this issues is to simplify the process, so that I'm not the only one who understands this part of scraper while keeping a things pretty efficient, even with big dumps.

Honestly I don't know what's the best solution, changing the principles (no database, 1 parsing) or improving the preparation by doing it differently....

**Comment by kelson42** [comment]
@rgaudin Can we close this ticket as you are over with this part of sotoki 2.0?

**Comment by rgaudin** [comment]
yes, we kept principle but rewrote for maintenance and speed. Sounds OK for now.
