### ISSUE TITLE
Get more robust filetype identification

### ISSUE THREAD

**Issue by dattaz** [openzim/sotoki#115]
On https://github.com/openzim/sotoki/blob/master/sotoki/sotoki.py#L841, function `get_filetype`
We identify using headers or mine type with magic.

If we did not find something we know with headers we should fall back on magic identification (currently : return "none")

**Comment by rgaudin** [comment]
Also we might want to switch the magic lib we use (https://github.com/ahupp/python-magic seems better)

**Comment by satyamtg** [comment]
Hey @dattaz @rgaudin , is this issue already fixed? I can see that the function falls back to magic for mime type identification.

**Comment by kelson42** [comment]
@satyamtg No, want to help and propose a PR?

**Comment by satyamtg** [comment]
Yes. I really want to do that. Looking into the issue.

**Comment by satyamtg** [comment]
Hey @kelson42 I have fixed this and made a PR. It also switches to python-magic as pointed out by @rgaudin. However, I feel this piece of code is quite shareable and should be implemented in scraperlib. Will add this to my proposal.
