### ISSUE TITLE
Crash on lack of disk space

### ISSUE THREAD

**Issue by rgaudin** [openzim/sotoki#116]
ATM, when there's not enough free space on disk (or `/dev/shm`), the process prints error and continues.
It's an error and it should properly crash.

**Comment by kelson42** [comment]
@rgaudin I’m not sure about the pertinence left of this ticket. We are going to fix the last reasons why we should have problems around free storage space. I’m as well not so sure if there is a valid way to fix that problem easily. Do you?

**Comment by rgaudin** [comment]
I don't get how this can not be pertinent…

That said, we are moving from a situation where there was a known bug leading to lack of space to a normal situation where lack of space can happen based on the host environment.

Now, sotoki can use up to 2 different mount points to write stuff to. Consequences are different:

* `/dev/shm`: not handled, results in mising images in the ZIM file **(bad**).
* `output` (on disk): will be handled (crash) at least at very end when preparing file or writing the ZIM file **(OK)**.

Last one might change using pylibzim as we'll write articles to ZIM file as they are produced (but maybe that's still at very end?)

Now, with this situation, the only thing we should care about is `/dev/shm`. In the zimfarm case, we control `/dev/shm` as it's a per-container mount of `64M` (default) that we could increase but for non-zimfarm users, there's a chance that there's not enough space available.

This chance is **very small** though as our usage is small (`nb_of_threads * max_downloaded_filesize`) so we may consider that there's not enough incentive in fixing this (not worth the efforts). In that case, please close the ticket.
