### ISSUE TITLE
Temporary files with 0 size left on disk

### ISSUE THREAD

**Issue by satyamtg** [openzim/sotoki#122]
Many temporary files with 0 size are left in dev/shm . We need to fix this as this will leave a "dirty" directory and potentially impact performance.

**Comment by rgaudin** [comment]
are the source files 0 bytes (downloaded) or is it the result of the optimization?

**Comment by satyamtg** [comment]
> are the source files 0 bytes (downloaded) or is it the result of the optimization?

@rgaudin , it seems that they are created by the optimization libraries as no filename matches with any temporary file name in the logs.

**Comment by satyamtg** [comment]
> > are the source files 0 bytes (downloaded) or is it the result of the optimization?
> 
> @rgaudin , it seems that they are created by the optimization libraries as no filename matches with any temporary file name in the logs. Although it seems that they are cleared properly by the library creating them, its still not good to have them as @kelson42 pointed out.

So I'm wrong here. These files are actually the files whose links give a 404 error. We need to check whether the link exists and only then create a temporary file and download. Will fix this in some time. PR incoming.

**Comment by kelson42** [comment]
@satyamtg This is not the best approach because you will slow down the whole process (Because of the HTTP latency) just to handle of a small fraction of missing images. A better approach is to always download and then check for failing downloads (none 200 HTTP status code),

**Comment by satyamtg** [comment]
@kelson42 fixed this. Used a better approach than the two options I mentioned. We use urlopen() to download first. If it fails, we print the error otherwise we create a temporary file and write the contents of the response in it.
