### ISSUE TITLE
External image dependences in recent ZIM

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#127]
In https://download.kiwix.org/zim/stack_exchange/physics.stackexchange.com_en_all_2020-04.zim, `zimcheck` complains that we have a few external images. This is not OK. I have verified the first ones and indeed they are included in the HTML:

```
  http://i.stack.imgur.com/mofu9.jpg is an external dependence in article A/question/6271.html
  http://media.skyandtelescope.com/images/Solar_filter_products_m.jpg is an external dependence in article A/question/29454.html
  https://i.stack.imgur.com/OdMpw.png is an external dependence in article A/question/31482.html
  http://www.orientalmotor.com/images/feature/bl-speedtorque-chart.jpg is an external dependence in article A/question/106352.html
  http://picpaste.com/xOqpzL1w.png is an external dependence in article A/question/107083.html
  https://i.imgur.com/W9mO0zK.png is an external dependence in article A/question/135371.html
  http://inspirehep.net/record/1121526/files/wavepacket-1.png is an external dependence in article A/question/159190.html
  http://s9.postimg.org/pal98fo67/static.png is an external dependence in article A/question/191461.html
  http://code.jquery.com/jquery-latest.min.js is an external dependence in article A/question/220306.html
  http://i.stack.imgur.com/Vembd.jpg is an external dependence in article A/question/225955.html
  https://i.stack.imgur.com/vAUuy.png is an external dependence in article A/question/253158.html
  https://i.stack.imgur.com/yHqzt.jpg is an external dependence in article A/question/361513.html
  https://i.stack.imgur.com/QGZQg.png is an external dependence in article A/question/403263.html
```

This pictures should be downloaded, optimized, and URL should be rewritten to point to the ZIM.

**Comment by satyamtg** [comment]
@kelson42 strange. I'll first replicate and see if this happens with any of the meta.stackexchange ZIMs as testing on large ZIMs would take a lot of time and possibly delay the fixes. I'll inform if I find something. Looking into it.

**Comment by kelson42** [comment]
For the moment, I believe this is somehow related to https://github.com/kiwix/kiwix-lib/issues/339. As this bug shoudl be fixed in the next days, I will wait for that first.

**Comment by satyamtg** [comment]
@kelson42 can you share one or two HTMLs which have this problem?

**Comment by kelson42** [comment]
@satyamtg You have already access to everything I have, nothing more, nothing less. If you want to have a look to how the HTML looks like, you can check on the demonstration online here: http://localhost:8080/physics.stackexchange.com_en_all_2020-04/

**Comment by dattaz** [comment]
http://library.kiwix.org/physics.stackexchange.com_en_all_2020-04/A/index.html and not localhost ;)

**Comment by kelson42** [comment]
@dattaz This is the same, I just tested locally with the ZIM file and kiwix-serve.

**Comment by dattaz** [comment]
Yes yes, I just click and not understanding why I see nothing

Anyway, the issue is that we did not download image from comment. We should add call to `image` function [here](https://github.com/openzim/sotoki/blob/master/sotoki/sotoki.py#L375) and [here](https://github.com/openzim/sotoki/blob/master/sotoki/sotoki.py#L384)

**Comment by kelson42** [comment]
@dattaz Thx for pointing the error, this with be helpful for @satyamtg. But for me, I don't really understand why in 99% we download the pictures in questions/comments... but why not these few ones?

**Comment by dattaz** [comment]
I did not check all error `zimcheck` report but only a few, each are in comment.

Currently : we download on questions and answers. we did not download in comments.

**Comment by kelson42** [comment]
@dattaz OK, seems to me to be a big bug which got under the radar. The good news is that this seems trivial to fix :) @satyamtg

**Comment by satyamtg** [comment]
> @dattaz OK, seems to me to be a big bug which got under the radar. The good news is that this seems trivial to fix :) @satyamtg

Yup. It's actually quite trivial to fix. Thanks to @dattaz for pointing that out.
