### ISSUE TITLE
A few dead internal links

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#129]
Loading recently created ZIM file in kiwix-serve. I read:
http://localhost:8080/physics.stackexchange.com_en_all_2020-04/A/question/521772.html

In this page there is the following HTML code:
```
<p>The <span class="math-container">$\mathbb{Z}_2$</span> order stems from the particle-hole symmetry of the superconducting Hamiltonian, and is discussed more <a href="134410.html">here</a> .</p>
```

There is in this HTML snippet, a link to http://localhost:8080/physics.stackexchange.com_en_all_2020-04/A/question/134410.html, but this article does not exist. It should or we should not have a link.

**Comment by dattaz** [comment]
What happen is that dump refer to `https://physics.stackexchange.com/q/134410` which should be a question, so we wrote link like it is a question. But it is not, it is a answer, and we then should write link in answers format.

I don't know how to deal with this for the moment but 2 idea : 
- We may verify each link to question are a valid question (but we don't currently store somewhere a list of all question id I think)
- Rework redirection format to have a unique format for questions/answers and maybe comment : ~ `/element/[element id].html#[element id]`and when we deal with element write redirection from `/element/[element id].html` to `/question/[question of element].html`. We need to check what are the implication of doing that

**Comment by kelson42** [comment]
@dattaz You mean the XML data is wrong?

**Comment by dattaz** [comment]
Also on http://library.kiwix.org/physics.stackexchange.com_en_all_2020-04/A/question/6271.html, last comment of post, we have internal link, but they are but they are not displayed as links

**Comment by dattaz** [comment]
> @dattaz You mean the XML data is wrong?

I mean that the person who wrote this answer redirected to a question (`https://physics.stackexchange.com/q/134410`) and not to an answer (`https://physics.stackexchange.com/a/134410`) (and so it is on XML dump).
Nevertheless stackoverflow supports this kind of thing and realizes the good redirection...

**Comment by kelson42** [comment]
> Also on http://library.kiwix.org/physics.stackexchange.com_en_all_2020-04/A/question/6271.html, last comment of post, we have internal link, but they are but they are not displayed as links

Not sure what is meant here, but I suspect this desserve an other ticket because this is another kind of bug.

**Comment by kelson42** [comment]
> I don't know how to deal with this for the moment but 2 idea

I don't properly undrstand the second solution, but the first one seems impossible to implement qithout using a something like Redis. Therefore, solution 2 needs to be investigated probably.

**Comment by satyamtg** [comment]
> Also on http://library.kiwix.org/physics.stackexchange.com_en_all_2020-04/A/question/6271.html, last comment of post, we have internal link, but they are but they are not displayed as links

@dattaz I do agree with @kelson42 regarding this. This indeed seems to be a big bug. I analyzed the XMLs and in some texts, links are just written as texts and not markdown and thus are never converted into clickable links. The comment block for this very comment is as follows in the XML
`<comment Id="589575" PostId="6271" Score="0" Text="Related: http://physics.stackexchange.com/q/68599/, http://physics.stackexchange.com/q/35660/, http://physics.stackexchange.com/q/35660/, http://physics.stackexchange.com/q/75397/, http://physics.stackexchange.com/q/6271/ , http://physics.stackexchange.com/q/77465/2451 and links therein." CreationDate="2016-07-01T12:02:21.587" UserId="2451" />`

I think we should add another layer of link parsing after markdown to HTML is done. Will open a new issue for this.

**Comment by satyamtg** [comment]
As far as this particular issue is concerned, I think that we should try to change the redirection format (the second solution proposed by @dattaz ) as checking whether a link is valid or not may affect performance as it can't be implemented unless we somehow store a list of question IDs. (which would in turn require more space and computation.

**Comment by satyamtg** [comment]
@kelson42 @dattaz I think I've fixed this. Changed the redirection scheme a bit. See branch [fix_dead_links](https://github.com/openzim/sotoki/tree/fix_dead_links).
Now, the redirection scheme is something like this - 
`[element_id].html -> question/[element_id].html` for questions and `[element_id].html -> question/[element_id of corresponding question].html` . I've also removed the redirection from slug link to our question link in favour of smaller size of redirection.csv

**Comment by rgaudin** [comment]
Don't forget to force-refresh pages to get new links :)
