### ISSUE TITLE
favicon not converted to png format

### ISSUE THREAD

**Issue by satyamtg** [openzim/sotoki#131]
Currently, `mogrify -format png` fails to convert favicon to PNG format. This is basically because the favicon.png is actually a Windows icon file with a .png extension which mogrify doesn't handle properly. The following is the output of libmagic on the favicon
`'MS Windows icon resource - 2 icons, 16x16, 32 bits/pixel, 32x32, 32 bits/pixel'`
We should add code to properly handle this type of file.

**Comment by kelson42** [comment]
Yes, like we can see it here http://library.kiwix.org/physics.stackexchange.com_en_all_2020-04/I/favicon.png. Size is wrong (should be `48x48`) and the format is wrong (should be PNG).
