### ISSUE TITLE
Handling of links written as plain text in XMLs

### ISSUE THREAD

**Issue by satyamtg** [openzim/sotoki#133]
As mentioned [here](https://github.com/openzim/sotoki/issues/129#issuecomment-612673324), sotoki currently doesn't handle links that are written as plain text instead of markdown. An example can be found [here](http://library.kiwix.org/physics.stackexchange.com_en_all_2020-04/A/question/6271.html) (in the last comment under the question) and another one [here](http://library.kiwix.org/physics.stackexchange.com_en_all_2020-04/A/question/1.html) (in the first comment under the question)

This should not be the case as this would leave many clickable redirections unhandled.

**Comment by kelson42** [comment]
@satyamtg @rgaudin @dattaz Might that be that with just need a better markdown parser?

**Comment by dattaz** [comment]
"A better markdown parser", it not easy to find a markdown parser that works well...(We come on non trivial markdown error on dump for exemple https://github.com/Python-Markdown/markdown/issues/551). Sotoki has already used and experienced 3 markdown parser... `mistune` (current markdown parser) is quite good, and his developer respond quickly if need (cf bug from few week ago).

But we may use something to find link in text and convert them to href.

Maybe we may use `mistune` pluging for URL => https://mistune.readthedocs.io/en/latest/plugins.html#url

**Comment by satyamtg** [comment]
@kelson42 I agree with @dattaz  on the fact that mistune is quite good. However, just using the URL plugin would not be enough in our case as there are 2 issues that it can't handle. 
1. It won't parse apex domains, say example.com - This can be an issue if it is same as the domain currently being scraped (we'll miss on links)
2. We give mistune markdown text with escaped HTML characters. (like &lt, &gt etc.). So in case the link was enclosed in markdown as <link>, it'll be &ltlink&gt and mistune will then parse the link as <a href="link%3E">link%3E</a> (it thinks &gt is part of the link and replaces with %3E) - BTW, @dattaz  @rgaudin do we have any specific reason to escape HTML characters before feeding to mistune?

I was trying to come up with a regex based solution to this problem. It's still under process.

For testing, I would recommend using the following markdown text:
```
[I'm an inline-style link](https://www.google.com)

[I'm an inline-style link with title](https://www.google.com "Google's Homepage")

[I'm a reference-style link][Arbitrary case-insensitive reference text]

[I'm a relative reference to a repository file](../blob/master/LICENSE)

[You can use numbers for reference-style link definitions][1]

Or leave it empty and use the [link text itself].

URLs and URLs in angle brackets will automatically get turned into links. 
http://www.example.com or <http://www.example.com> and sometimes 
example.com (but not on Github, for example).

Some text to show that the reference links can follow later.

[arbitrary case-insensitive reference text]: https://www.mozilla.org
[1]: http://slashdot.org
[link text itself]: http://www.reddit.com
```
Currently if we use just mistune with the URL plugin, we would get the following convertion
```
<a href="https://www.google.com">I'm an inline-style link</a></p>
<p><a href="https://www.google.com" title="Google's Homepage">I'm an inline-style link with title</a></p>
<p><a href="https://www.mozilla.org">I'm a reference-style link</a></p>
<p><a href="../blob/master/LICENSE">I'm a relative reference to a repository file</a></p>
<p><a href="http://slashdot.org">You can use numbers for reference-style link definitions</a></p>
<p>Or leave it empty and use the <a href="http://www.reddit.com">link text itself</a>.</p>
<p>URLs and URLs in angle brackets will automatically get turned into links. 
<a href="http://www.example.com">http://www.example.com</a> or &lt;<a href="http://www.example.com%3E">http://www.example.com%3E</a>; and sometimes 
example.com (but not on Github, for example).</p>
<p>Some text to show that the reference links can follow later.
```

**Comment by kelson42** [comment]
@dattaz @satyamtg This evaluation is a few years old, things might have moved one. But the key questions are (1) does this plain URL parsing is part of the Markdown standard (2) Where is the upstream ticket for that bug/feature?

**Comment by satyamtg** [comment]
> @dattaz @satyamtg This evaluation is a few years old, things might have moved one. But the key questions are (1) does this plain URL parsing is part of the Markdown standard (2) Where is the upstream ticket for that bug/feature? I'm pretty opposed to any custom Markdown parsing in Sotoki.

@kelson42 , I'm also quite not in favour of custom URL parsing if it's not strictly needed. Coming to your questions - 
1. Plain URL parsing even without angular brackets is not standard markdown. However, mistune has the URL plugin that can do so (although it doesn't work for domains not preceded by http:// or https:// ; like example.com , 3dprinting.stackexchange.com).
2. In my opinion, we do not need a upstream ticket for that because it's something which we face and not a bug with mistune.

What in my opinion is the best solution is to pass the non HTML escaped version of the text to mistune with URL plugin enabled and ignore the types of links in the 1st point. (@dattaz why do we pass HTML escaped text to mistune? I couldn't find a necessity for it in the docs) Or just parse the domain name that we are currently scraping to ensure that we get all the internal links correct. 

Custom parsing of links with regex (as I tried before) would be a problem to implement in a stable and fast fashion.

**Comment by dattaz** [comment]
Agree with @satyamtg, no custom URL parsing, we must not end up with over-linking also...

Markdown comment (and title) escaping was introduce because of #50 (which is unfortunately given very few details...), but, if I remember correctly, it is because people can explicitly write HTML tags in the comments and these elements are not already escaped in the dump of comments, so the comments must be understood as plain text.

I just check in Comments.xml from a dump, its seems (now ?) that HTML char are escaped...so we end up to same problem...Maybe we should check if link with `<URL>` are escaped or not...

I think that we should keep it easy, and just parse with the automatic detection of link, it better than before (not perfect, but already better than what we have in the dump)

**Comment by satyamtg** [comment]
@kelson42 @dattaz @rgaudin I don't see a need to escape HTML characters now. Using mistune with URL plugin handles that. For example, I gave the following input
```
hello I am testing <html>haha</html>, <body>, <p> something & something else </p> , http://satyamtg.co and <https://google.com> is parsed correctly or not.
```
This is processed as 
```
hello I am testing &lt;html&gt;haha&lt;/html&gt;, &lt;body&gt;, &lt;p&gt; something &amp; something else &lt;/p&gt; , <a href="http://satyamtg.co">http://satyamtg.co</a> and <a href="https://google.com">https://google.com</a> is parsed correctly or not.
```
This output seems to be good for us. This would work just fine. For an extra, we can just match with domain that we currently are parsing to not miss any internal links due to human errors.
