### ISSUE TITLE
Sotoki fails to create a post if a comment has no text

### ISSUE THREAD

**Issue by satyamtg** [openzim/sotoki#137]
Currently, if a comment under a post has no text, then Sotoki skips creating the post. This creates loss of information. I have found out that the comments consisting only of Emojis have their text empty in the XML file. Sotoki should instead skip creating that specific comment / or create a comment with no text / create a comment stating text contains no characters and create the post successfully.

In physics.stackexchange.com dump, the following 2 posts have this problem. 
- Post ID -  451827
- Post ID - 528399
The actual post [here](https://physics.stackexchange.com/questions/451827/deep-concept-of-rotation-dynamics) has a comment with all emojis. The XML for that comment in the dump is -
```
<comment Id="1013673" PostId="451827" Score="0" Text="" CreationDate="2019-01-03T08:18:49.780" UserId="218714" />
```
Sotoki currently just prints the error and moves on without creating the entire post

```
Already 126000 questions done!
Error with a post : Document is empty
Already 127000 questions done!
Already 128000 questions done!
Already 129000 questions done!
Already 130000 questions done!
Already 131000 questions done!
Already 132000 questions done!
Already 133000 questions done!
Already 134000 questions done!
Already 135000 questions done!
Already 136000 questions done!
Already 137000 questions done!
Already 138000 questions done!
Already 139000 questions done!
Already 140000 questions done!
Already 141000 questions done!
Already 142000 questions done!
Already 143000 questions done!
Already 144000 questions done!
Already 145000 questions done!
Already 146000 questions done!
Already 147000 questions done!
Already 148000 questions done!
Already 149000 questions done!
Already 150000 questions done!
Already 151000 questions done!
Already 152000 questions done!
Error with a post : Document is empty
Already 153000 questions done!
Already 154000 questions done!
---END--
Render tag page
Creating ZIM files
	Writing ZIM for Physics Stack Exchange
zimwriterfs --flavour="nopic"  --inflateHtml --redirects="work/physics_stackexchange_com/redirection.csv" --welcome="index.html" --favicon="favicon.png" --language="eng" --title="Physics Stack Exchange" --description="Q&A for active researchers, academics and students of physics" --creator="Physics Stack Exchange" --publisher="Kiwix" --tags="_category:stack_exchange;stackexchange;nopic" --name="kiwix.physics.stackexchange.com.nopic" --scraper="sotoki 1.2.1" --source="https://physics.stackexchange.com" "work/physics_stackexchange_com/output" "work/physics.stackexchange.com_en_all_2020-04_nopic.zim"
Resolve redirect
Invalid redirection A/element/451827.html redirecting to (missing) A/question/451827.html
Invalid redirection A/element/451832.html redirecting to (missing) A/question/451827.html
Invalid redirection A/element/528399.html redirecting to (missing) A/question/528399.html
Invalid redirection A/element/528410.html redirecting to (missing) A/question/528399.html
Invalid redirection A/element/528434.html redirecting to (missing) A/question/528399.html
set index
Successfuly created ZIM file at work/physics.stackexchange.com_en_all_2020-04_nopic.zim
```

**Comment by dattaz** [comment]
So emoji in comment aren't present in dump ?

Can we report it to stackexchange ? @kelson42

**Comment by kelson42** [comment]
@dattaz We could probably... but I don't understand what is going on here.

**Comment by satyamtg** [comment]
> So emoji in comment aren't present in dump ?
> 
> Can we report it to stackexchange ? @kelson42

I can confirm that no data related to comments with all emojis are present in the dump. That is, the text field is empty and no other data is there. I think we should report it.

**Comment by NickCraver** [comment]
Oooh interesting - that's the first time I've seen this reported. Thanks for doing so!

We're fighting some other SQL issues at the moment (with the SQL Server 2019 upgrade) but will take a look. We're using some built-in bits here so it may not be a quick fix. Regardless, we'll investigate and report back!

**Comment by kelson42** [comment]
@NickCraver Do you have a place somewhere on your side where we can track this issue?

**Comment by kelson42** [comment]
@satyamtg Maybe we should open a ticket on our side regarding this specific problem. What do you think?
