### ISSUE TITLE
https in place of http

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#175]
At least in the bottom link « This question is issued from http://dsp.stackexchange.com«.

**Comment by Neilblaze** [comment]
@kelson42 link is not working. If this is still up for grabs can I take this?

**Comment by kelson42** [comment]
This link is in the ZIM file http://download.kiwix.org/zim/stack_exchange/dsp.stackexchange.com_en_all_2020-04.zim

**Comment by Neilblaze** [comment]
I'm on it! :rocket:

**Comment by dattaz** [comment]
Hello @Neilblaze are you still working on it ?
I think the best way to do is to modify this part of the code => https://github.com/openzim/sotoki/blob/master/sotoki/sotoki.py#L1651:L1655

**Comment by kelson42** [comment]
@dattaz If you consider to fix this, I think you can carry on.

**Comment by Neilblaze** [comment]
@dattaz apologies for the delay, I created a [PR](https://github.com/openzim/sotoki/pull/193). Please have a look :)


I was facing some issues running the same on Windows (WSL), later I figured out that Ubuntu may be the way to go for me. I'm pretty new to Openzim & I want to explore this. Is there any forum or community where I can reach out to?

**Comment by kelson42** [comment]
@Neilblaze Thank you for your PR. Sotoki does not run on Windows indeed. Good idea to use Ubuntu. Many of us use it and this is a better OS. You can join our Slack workspace with https://join.slack.com/t/kiwixoffline/shared_invite/enQtOTUyMTg4NzMxMTM4LTU0MzYyZDliYjdmMDYzYWMzNDA0MDc4MWE5OGM0ODFhYjAxNWIxMjVjZTU4MTkyODJlZWFkMmQ2YTZkYTUzZDY but most of the discussions run on the tickets, here on Github.

**Comment by ritikjaiswal019** [comment]
@kelson42 @dattaz Is this issue still open. If yes can I work on this?

**Comment by kelson42** [comment]
I believe so. Your are welcome to work on it.
