### ISSUE TITLE
Respect SE attribution rules

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#18]
All page should attribute content to SE and respective authors:
https://archive.org/details/stackexchange
- [x] Visually display or otherwise indicate the source of the content as coming from the Stack Exchange Network. This requirement is satisfied with a discreet text blurb, or some other unobtrusive but clear visual indication.
- [x] Ensure that any Internet use of the content includes a hyperlink directly to the original question on the source site on the Network (e.g., http://stackoverflow.com/questions/12345)
- [x] Visually display or otherwise clearly indicate the author names for every question and answer used
- [x]  Ensure that any Internet use of the content includes a hyperlink for each author name directly back to his or her user profile page on the source site on the Network (e.g., http://stackoverflow.com/users/12345/username), directly to the Stack Exchange domain, in standard HTML (i.e. not through a Tinyurl or other such indirect hyperlink, form of obfuscation or redirection), without any “nofollow” command or any other such means of avoiding detection by search engines, and visible even with JavaScript disabled.

**Comment by amirouche** [comment]
Not sure whether the direct links to SE are necessary since sotoki dump are meant to be offline.

**Comment by dattaz** [comment]
Done on merge_xml

**Comment by kelson42** [comment]
Great! @amirouche, could we merge "merge_xml" to master? Maybe a few things from the "wiredtiger" branch might also benefit to master? Would be great to come back to one working branch.
