### ISSUE TITLE
Hide age of questions

### ISSUE THREAD

**Issue by Popolechien** [openzim/sotoki#181]
Current sorting displays the most popular questions (by vote), which tends to favor older ones. The current layout prominently displays the question's age, which tends to put 7 to 8 years-old post on top and makes the zim file looks _extremely_ stale and makes for poor UX. Age of questions should be hidden at least on the landing page.

![Capture d’écran 2020-12-09 à 17 18 09](https://user-images.githubusercontent.com/21675885/101656051-8e9f7700-3a42-11eb-92c4-405d8e8391f0.png)

**Comment by CodingApps** [comment]
Hi, could I take this issue to complete it?

**Comment by dattaz** [comment]
Yes you can, look inside `sotoki/templates/index.html`

**Comment by CodingApps** [comment]
@Popolechien @dattaz Took a look. Should I revise the layout and then just submit the pull? Or will you assign to me beforehand?

**Comment by Popolechien** [comment]
@CodingApps maybe post a proposal/mockup first and then go for the PR

**Comment by kelson42** [comment]
Honestly, I'm unsure if all of this is a good idea"

**Comment by Popolechien** [comment]
@kelson42 The problem as stated above is that the first impression users have when opening a SE/SO file is that they downloaded really old stuff. Presenting users first with potentially stale content (or making it so obvious as it is at similar font size/level as the question( gives a bad first impression.

**Comment by CodingApps** [comment]
@Popolechien I see where this can be changed. Do you have steps for installing this environment on a Mac? Tried the Getting Started steps and keep getting a "ImportError: failed to find libmagic" error, even though it's already installed.

**Comment by kelson42** [comment]
@kelson42 So the problem is that the user does not understand properly that the ZIM snapshot and you want to improve this sensation/knowledge?

**Comment by Popolechien** [comment]
@kelson42 Correct.
It's not about hiding accurate information (the date should remain in the question/answer page as it may be relevant), but leaving some info out at first contact. What's important for users is 1. what popular questions are there (user might have the same)? 2. do they have answers?
There is an issue of onboarding and credibility if the product looks stale from the outset.

**Comment by kelson42** [comment]
@Popolechien OK. I understand the problem, let me just think a bit about it. We will do something about that.

**Comment by kelson42** [comment]
We still need to discuss this topic. But a solution has to be elaborated.

**Comment by rgaudin** [comment]
@Popolechien I believe this is now invalid as we are following SE's design in showing date (not elapsed time from now) in the questions page. This date, while present, is not emphasized.

SE has a different homepage than us with Active questions only that we don't offer in offline version. Please take a look at newer version and reopen if you think it's still an issue
