### ISSUE TITLE
Scraper should not pick up unanswered questions

### ISSUE THREAD

**Issue by Popolechien** [openzim/sotoki#182]
Since offline users are not able to answer questions, the zim file should be seen for the answer resource it is rather than for its forum part. It should also allow to reduce substantially total file size.

**Comment by rgaudin** [comment]
I disagree. At least for code related ones, knowing the question exists but was not answered is valuable.

**Comment by kelson42** [comment]
Even of the value is limited, a question without answer is not totally useless.

@Popolechien Do we have a good reason, not have gien so far, to not close this ticket as WONTFIX?

**Comment by Popolechien** [comment]
Well maybe for code-related comments, but for such threads as Great Outdoors or even language learning I'm pretty sure a question without answer is pretty maddening. Looking at Graphic Design right now and about 30 to 50% of questions over the last 2 months have remained unanswered. Ultimately there's a legitimate trade off between potentially relevant information and the underlying objective of reducing file size to increase reach.

Some of the unanswered questions still get upvotes, which supports your argument. That could be a way to sort things : 0 (or even negative) upvotes _**and**_ 0 answers = delete, x (with x>0) upvotes **_or_** answers = keep

**Comment by dattaz** [comment]
I also think that a question, even an unanswered one, makes sense. Especially when the author suggests possible answers.

I don't know the distribution of size between text and image in sotoki zims. But although an unanswered question can have an image, I think that a big part of the size of the zim comes rather from the non-textual contents.

**Comment by Popolechien** [comment]
Ok, not a hill I'm going to die on. I'll bend to majority opinion until we get more data.

**Comment by dattaz** [comment]
Another point that came to me is that if you don't take some questions, you start to edit the content (it's not the whole site anymore, but only a part of it), I dont think this is good idea

**Comment by Popolechien** [comment]
Reopening as it is a SO demand within their Bard project. 
Quote: "_narrowing down to the 20M answered questions would make for a smaller subset and I would suggest that unanswered questions are interesting when the user can get online and contribute, but would be frustrating in an offline Read Only environment."_

**Comment by rgaudin** [comment]
OK, we can have a *selection* triggered by an option. Your quote mentions limiting it to 20M answered responses as well.

**Comment by Popolechien** [comment]
20M is the number given to me by folks at SE/SO, ie their estimate of how many _answered_ questions would be available in a "responded-only" package.

**Comment by kelson42** [comment]
Should be an option and only activated for Bard.
