### ISSUE TITLE
Option : Remove usernames from posts

### ISSUE THREAD

**Issue by Popolechien** [openzim/sotoki#183]
Usernames should not be displayed in posts and all submissions should be anonymous (à la 4chan?)

**Comment by rgaudin** [comment]
This should be an option ; we certainly don't want to strip out usernames in the *regular* version. Please confirm so we can fix the title.

**Comment by Popolechien** [comment]
> we certainly don't want to strip out usernames in the regular version

Not sure I see a value there, but in any case as indicated by the `Bard` tag this is for a specific project (prison distribution) and a request from the sponsor.

**Comment by kelson42** [comment]
Should be an option and will be activated for a Bard dedicated version of ZIM file(s).

**Comment by rgaudin** [comment]
Implemented using `--without-names`.

Replaces name with a unique string so it's consistent across the ZIM (or any zim actually).

Sample: `Andrew Cheong` becomes `OOSEHNTDR`. All generated names are uppercase.
