### ISSUE TITLE
Option to remove external links to personal pages

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#186]
Instagram, facebook, ... al of them should be totally deleted or just mark as deleted. This should be based on a regex list.

**Comment by dattaz** [comment]
Can this be the same than #185 ? (no external link) as it will be use in the case context (bard)

**Comment by rgaudin** [comment]
no, there are two tickets on purpose. For social stuff, they need even the label/url to not be visible (kinda same purpose as nousername)

**Comment by rgaudin** [comment]
This should also filter-out any email address

**Comment by rgaudin** [comment]
Implemented via `--without-users-links`

What is does is that looks at all links and remove completely those that are from the same first-level domain as the following list.
It's different than `--without-external-links` which removes the URL of the link so its text content stays on the page.

In the case of `--without-users-links`, the link `<a href="facebook.com/mysupername">My Super Name Profile</a>` is completly replaced with `[redacted]`.

It doesn't look at regular text so a non-link `I'm also at facebook.com/mysupername.` would not be affected.

```py
SOCIAL_DOMAINS = [
    "facebook.com",
    "youtube.com",
    "whatsapp.com",
    "m.me",
    "instagram.com",
    "icq.com",
    "qq.com",
    "tiktok.com",
    "douyin.com",
    "weibo.com",
    "telegram.com",
    "twitter.com",
    "snapchat.com",
    "twitch.tv",
    "kuaishou.com",
    "pinterest.com",
    "reddit.com",
]
```

Additionally, `mailto:` links are removed regardless of the email it points to.
