### ISSUE TITLE
Use higher resolution image as ZIM favicon

### ISSUE THREAD

**Issue by rgaudin** [openzim/sotoki#194]
The ZIM favicon is taken from the source website favicon which is not a good idea:
- site favicon is 32x32px
- zim favicon are 48x48 (convention)
This make the ZIM favicon look ugly everywhere.

Stack Exchange sites offer a 158x158px image as `image_src` or `apple-touch-icon` which we should use instead.

**Comment by RajSrinivasJena** [comment]
@rgaudin can I take this Issue ?

**Comment by kelson42** [comment]
@RajSrinivasJena Thank you for your offer. Unfortunately, This is not really a good timing, because we are just before rewriting the whole sotoki. I would recommend to take another good-first-issue in an other repository.

**Comment by rgaudin** [comment]
this is already done in master.
