### ISSUE TITLE
INT-FLOAT TypeError  (relating to ready_queue -> python's Multiprocessing Queues)

### ISSUE THREAD

**Issue by gajanangitte** [openzim/sotoki#201]
### Step 1: Are you ready to report ?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - [.] I have test with the last (dev) version of the software?  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2 : What is your environment ?
  * browser / app : Linux terminal, Armx86, 8 gb ram, hp pavillion
  * version of the software you use : 
  *  device / operating system : linux
  
### Step 3: Describe the problem:

Extracting archive: computergraphics.stackexchange.com.7z
--
Path = computergraphics.stackexchange.com.7z
Type = 7z
Physical Size = 9153953
Headers Size = 302
Method = BZip2
Solid = +
Blocks = 1
Everything is Ok
Files: 8
Size:       51614503
Compressed: 9153953
~/Desktop/gsoc/kiwix/bin/work/computergraphics_stackexchange_com ~/Desktop/gsoc/kiwix/bin
~/Desktop/gsoc/kiwix/bin
Prepare: it's done !
Prepare xml ok
Traceback (most recent call last):
  File "./sotoki", line 33, in <module>
    sys.exit(load_entry_point('sotoki==1.3.2.dev0', 'console_scripts', 'sotoki')())
  File "/home/gajanan/Desktop/gsoc/kiwix/lib/python3.8/site-packages/sotoki-1.3.2.dev0-py3.8.egg/sotoki/sotoki.py", line 1814, in run
    UsersRender(
  File "/home/gajanan/Desktop/gsoc/kiwix/lib/python3.8/site-packages/sotoki-1.3.2.dev0-py3.8.egg/sotoki/sotoki.py", line 630, in __init__
    self.request_queue = Queue(cores * 2)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 103, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 48, in __init__
    self._sem = ctx.BoundedSemaphore(maxsize)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 88, in BoundedSemaphore
    return BoundedSemaphore(value, ctx=self.get_context())
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 145, in __init__
    SemLock.__init__(self, SEMAPHORE, value, value, ctx=ctx)
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
TypeError: integer argument expected, got float

#### Steps to reproduce:

  1. CLONE SOTOKI AND all the dependencies *as metioned*
  2.  install using setup.py
  3.  sotoki computergraphics.stackexchange.com  https://stackoverflow.com --clean-previous
  
  * What should be the behaviour from your point of view? How do you expect the service to work?

### Step 4 (optional) : Other Comments:
  * What is the context of this ticket? If not obvious, explain why you need to do this.
 
  * If you have an idea about the technical background of the ticket, please share it.
i am not sure but tracing back , it seems to be a multiprocessing module's problem

**Comment by rgaudin** [comment]
Looks like you're not using the correct python version. Which is it? Please try with python 3.6-3.8

**Comment by dattaz** [comment]
The issue seems to be here : https://github.com/openzim/sotoki/blob/master/sotoki/sotoki.py#L1710 
/ in python3 return a float

**Comment by gajanangitte** [comment]
@rgaudin: tried with python 3.8....then created a virenv with 3.6 too... Still the same error

**Comment by rgaudin** [comment]
yes sorry @dattaz pointed out the problem. You can fix it easily or just run it with `--threads n` with `n` of your chosing.

**Comment by kelson42** [comment]
@rgaudin I guess we can close this ticket as this part has been completly rewritten? I guess the new code does not suffer of this issue!
