### ISSUE TITLE
Kiwix-serve topbar magnifying logo is too smal

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#211]
see:

![image](https://user-images.githubusercontent.com/1029718/123268905-c2358080-d4fe-11eb-9556-9c058d9aeacc.png)

**Comment by rgaudin** [comment]
From the commit comment:

> StackExchange's CSS is setting some property on all elements : margins on `<inputs />` and font-size on body that ends-up conflicting with the inserted Kiwix toolbar in kiwix-serve.
> 
> IMO, this is a Kiwix-serve bug and scrapers should not care about how the reader might affect its content. Related issue: https://github.com/kiwix/libkiwix/issues/394
> 
> As a short-term measure, some kiwix-related styles have been overwritten in the scraper.

This is quite fragile. What happens when kiwix-serve's toolbar UI is changed? The in-zim CSS will enforce those _fixes_ and might break it…
