### ISSUE TITLE
ZIM filenames differs from v1.x

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#250]
1.3.1 generates `beer.stackexchange.com_en_all_2021-05.zim` but future 2.0.0 generates `beer_stackexchange_com_2021-12.zim`. Is that on purpose? This does not ease the migration on [dow](https://download.kiwix.org/zim/stack_exchange/)

**Comment by rgaudin** [comment]
Yes, it was on purpose but I understand how our scripts would not recognize new ZIMs as updates of the former ones.

I think new names are better in general (better I don't really care) so I would suggest we keep those in the scraper and fix that in zimfarm recipes …  unless you want to to update dow scripts to accomodate new files.

**Comment by kelson42** [comment]
Agree, but not sure how exactly you want to adapt recipes and how we shoukd deal with olds files.
