### ISSUE TITLE
why there is no run for stackoverflow on openzim farm

### ISSUE THREAD

**Issue by yekanchi** [openzim/sotoki#257]
while I was able to download stackoverflow from openzim a while ago like:
[https://farm.openzim.org/pipeline/fefb8d486f98761b3c570a16](https://farm.openzim.org/pipeline/fefb8d486f98761b3c570a16)

but now there is no run for stackoverflow english.

close this if it's unrelated to the repo.

**Comment by yekanchi** [comment]
it seems there is a new todo:
[https://farm.openzim.org/pipeline/filter-todo](https://farm.openzim.org/pipeline/filter-todo)

I hope it will help us download for stackoverflow.com

**Comment by rgaudin** [comment]
This one is a special version with several limitations; I'm removing it. But we're starting a regular SO one in the coming days.

Appropriate repo for such requests would be openzim/zim-requests

**Comment by yekanchi** [comment]
thanks.
I'm closing as this is unrelated to this repo.
