### ISSUE TITLE
Release 2.1.0

### ISSUE THREAD

**Issue by rgaudin** [openzim/sotoki#275]
This issue serves as a checklist for the release event.

- [x] Check that dependencies have been updated to latest version (especially python-scraper lib)
- [x] Adjust version in `VERSION` to `x.x.x`
- [x] Update Github milestone to match the issues that will be released 
- [x] Close Github milestone
- [x] Update the Changelog so that it is in line with the content of Github milestone
- [x] Push a tag on Github named `vx.x.x` (this will trigger the CI)
- [x] Create a Github release, pointing to the tag, with the Changelog of this release
- [ ] ~Publish the Github release (this will trigger the CI, if the CI fails and you have to push a minor fix which does not justify to create a new version, you will have to delete the release and re-create it from scratch)~
- [x] Check that version is published as a Github release at https://github.com/openzim/sotoki/releases and tagged `Latest`
- [x] Check that version is published on Github Container Registry at https://ghcr.io/openzim/sotoki and tagged `latest`
- [ ] ~Check that version is published on Pypi at https://pypi.org/project/sotoki2zim/~
- [x] Create a new Github milestone with the next minor version incrementaly
- [x] Create a new Github issue attached to this milestone with this checklist inside
- [x] Create new `## [Unreleased]` section in Changelog (placeholder for future entries)
- [x] Adjust version in `VERSION` to `x.y.z-dev0
- [ ] Inform #scrapers Slack channel that a new release is ready to use 
- [x] Update Zimfarm recipes to use new release
- [ ] If needed, open a PR on Zimfarm to add support for new CLI parameters of interest

**Comment by kelson42** [comment]
Closing as it seems everything which has to be done has been done
