### ISSUE TITLE
Markdown text formatting is not rendered

### ISSUE THREAD

**Issue by mazen-mardini** [openzim/sotoki#286]
Text formatting such as the use of double-stars for **bold** and underscore for _italics_ isn't rendered to HTML.

For example, here is a comment online: https://crypto.stackexchange.com/questions/6185/what-is-a-tweakable-block-cipher#comment176536_6187

The same comment offline: https://library.kiwix.org/content/crypto.stackexchange.com_en_all_2022-11/questions/6185/what-is-a-tweakable-block-cipher#comment196369_6187

Supported formatting at StackOverflow can be found [here](https://stackoverflow.com/help/formatting). I suspect that all StackExchange sites use the same set of Markdown features.

**Comment by rgaudin** [comment]
Thank you for the report. It looks like markdown rendering is commented in the code. I remember we tested various markdown renderer tying to find the memory leak and [even tried without markdown support](https://github.com/openzim/sotoki/commit/0adac3d4140faf9ce9280217c125b7edcc159a38). For some reason, that got into main.

I'll restore it.

**Comment by rgaudin** [comment]
<img width="1169" alt="Screenshot 2023-04-10 at 14 33 38" src="https://user-images.githubusercontent.com/57929/230922897-0937ea1f-ee5b-405e-8a44-bde053e009c3.png">
