### ISSUE TITLE
AttributeError: module 'xml.sax' has no attribute 'saxutils'

### ISSUE THREAD

**Issue by benoit74** [openzim/sotoki#298]
"Suddenly" the `main` branch is not working anymore, it complains that `AttributeError: module 'xml.sax' has no attribute 'saxutils'` ; looking at the code we indeed `import xml.sax` and not `xml.sax.saxutils` ... I don't know how it worked before but fix seems pretty obvious.

**Comment by rgaudin** [comment]
Existed at least in 3.8 https://docs.python.org/3.8/library/xml.sax.utils.html#module-xml.sax.saxutils

**Comment by rgaudin** [comment]
Sorry I misread the ticket 😀
