### ISSUE TITLE
watch my questions and answers on stackexchange websites like stackoverflow

### ISSUE THREAD

**Issue by milahu** [openzim/sotoki#306]
workaround for [Send notification when question is closed or deleted](https://meta.stackoverflow.com/questions/258057/send-notification-when-question-is-closed-or-deleted)

the feature request for "notify me when my content is deleted" was rejected by stackoverflow
so the moderators have less work when dealing with "annoying users"...

<blockquote>

tl;dr:
this idea is always appealing to people
who don't answer support questions here on meta or via email,
and have no clue just how many questions get deleted.

The naive implementation you suggest
would generate entirely too much unproductive whining to be practical.
You're welcome to suggest a process
that would notify only people likely to take constructive action
in only those cases where such action is possible -
but as it stands, this idea is impractical and hence declined.

---

This is the same like not alerting on negative reputation.
Why are you so afraid of "hurting our feelings"?
Honestly if an alert saying your question is deleted is so hurtful,
you have bigger problems in life.
Turn it into a preference if you like,
but some people do not care about notifications being negative or positive,
they just want to be notified.

---

Rejecting a feature request for fear of whining is hardly a reason.

</blockquote>

i put time and effort into my content
and when a publisher rejects the publication
then i want to know, so i can find a different publisher for my work

can `sotoki` do this already?
continuous scraping of content by some user
including context (answers on questions, comments on answers)

... maybe also including all my upvoted questions and answers
but much less than a full scrape or data dump

stackexchange websites dont provide a way to "download all my data"
which is possible on other websites like google or facebook
so this would also be a workaround for this missing feature

> You can go put it somewhere more appropriate if you think it has long term value

yepp, let me mirror my content to git repos

ping @poke @servy (?) @cellio @angelo-fuchs

**Comment by benoit74** [comment]
Nope, `sotoki`:
- cannot filter out only few questions / answers based on author
- is not running the stuff on real-time data (we use archives produced at most once a month by stackexchange)
- does not have any notification mechanism

Since the goal of sotoki is to create an offline archive of stack exchanges sites, your need is even far away

Closing this as it is clearly too far from scraper intent / architecture / roadmap
