### ISSUE TITLE
minify HTML file ?

### ISSUE THREAD

**Issue by dattaz** [openzim/sotoki#31]
Actually a zim file of a stackechange web site is  around 10 time  bigger.
So for stackoverflow it's wilm make a zim of ~250Go...
I don't know how zim compression work but maybe de should try to see if minify file is better

**Comment by dattaz** [comment]
Image take also lot of space (and I forgot about them)

**Comment by kelson42** [comment]
My feedback about it: let's try to make a first version and bother about optimisation then. But anyway, yes this is probably going to be huge! :(

**Comment by amirouche** [comment]
There is already some code doing compression it should be tuned cf. [optimize](https://github.com/kiwix/sotoki/blob/master/sotoki.py#L347)

**Comment by dattaz** [comment]
For minify we can just minify templates
