### ISSUE TITLE
Seems impossible to specify a tag

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#312]
See https://farm.openzim.org/pipeline/6b73b999-8fda-4a77-b7ef-3c7a9ed93a80/debug

**Comment by benoit74** [comment]
This is a Zimfarm configuration issue. 

Proper CLI flag is `--tag` and not `--tags`. Passing multiple tags require that the `--tag` flag is called multiple times like `sotoki --tag "Quality Assurance" --tag "Another TAG"` and this is currently not supported by the Zimfarm. I will adjust Zimfarm configuration to at least support one additional tag.

Nevertheless, I expect that we want / need to support multiple tags. Do we want to fix this in sotoki (move from `--tag` to `--tags` and process this as a CSV, this is easy but a breaking change) or in Zimfarm (add support for list flags, this most probably needs UI adaptations and will most probably come with its own share of subtle bugs). WDYT?

**Comment by kelson42** [comment]
> Nevertheless, I expect that we want / need to support multiple tags.

Definitely, and it should be able to provide everything with a string, using `;` for example as separator. This is something we have done in a few other scrapers AFAIK.

**Comment by benoit74** [comment]
Yep, this is what I meant. Issue is here: https://github.com/openzim/sotoki/issues/315

**Comment by benoit74** [comment]
Zimfarm + recipe reconfigured, we can now specify 1 single tag.

Task: https://farm.openzim.org/pipeline/d3e4cbf0-50a5-4385-a6ac-7167b3307ec8

The task failed due to another bug most probably linked to known problems with SE data dump

This issue is hence fixed and other issues are opened, let's close this.
