### ISSUE TITLE
Revert useless changes in 2.1.1

### ISSUE THREAD

**Issue by benoit74** [openzim/sotoki#313]
Changes done in 2.1.1 were not necessary, these were only "mistakes" from SE: https://meta.stackexchange.com/a/398606

We have to revert at least the part doing the conversion from UTF16 + the adaptation of XML "parsing" (spaces at the beginning / end, CRLF vs CR, ...)

I suggest to keep the part taking care of removing deleted posts / comments since even if this is also not supposed to be present in the data dump, I do not expect this check to cause much trouble + it might be present in the data dump in the future.

**Comment by rgaudin** [comment]
Makes sense
