### ISSUE TITLE
Processing renamed stackexchange domain beer.stackexchange.com is failing 

### ISSUE THREAD

**Issue by benoit74** [openzim/sotoki#319]
beer.stackexchange.com has been renamed to alcohol.stackexchange.com

The dump is however still produced as beer.stackexchange.com.7z

If we use the new domain name alcohol.stackexchange.com, the scraper simply fails to find the corresponding site details and the dump.

If we use the old domain name beer.stackexchange.com, the scraper find some stuff (e.g. the dump) but still fails in the end.

See https://github.com/openzim/zim-requests/issues/1004 for details

**Comment by rgaudin** [comment]
this is absolutely not new. I don't recall how but we have something that matches the two

**Comment by benoit74** [comment]
There is no bug but a 137 exit code because memory was capped at 1G, which is not enough (anymore), see #325
