### ISSUE TITLE
wiredtiger backend

### ISSUE THREAD

**Issue by amirouche** [openzim/sotoki#35]
Use wiredtiger as database backend and see what happens.
- add a timeout to the  calls to optimize function cf. https://pypi.python.org/pypi/subprocess32/

**Comment by kelson42** [comment]
What is the status on this? Do we see an improvement in comparison to sqlite? Is that more complex to use?

**Comment by amirouche** [comment]
It's not more complex. That said, there is a memory leak that make it unsuable on big dumps. I'll have a look at it this week.

**Comment by amirouche** [comment]
I think that I remember that the leak comes from the image optimization step... I don't recall why I overlooked that issue. I trying to verify that.

**Comment by kelson42** [comment]
We have finally found a solution without using wiredtiger.
