### ISSUE TITLE
Make it possible to link to a particular answer in a question like it's possible on SO sites

### ISSUE THREAD

**Issue by amirouche** [openzim/sotoki#38]

**Comment by dattaz** [comment]
Format url for this is in SO is : http://stackoverflow.com/a/42872127 (where 42872127 is postid)
I'm not sure we can do that on zimfile.
What we can do is : [question url]#[postid] (ex: [question url]#42872127

**Comment by kelson42** [comment]
@dattaz No 100% sure I understand the ticket. But I would create a redirect with the number to the question (with the title).

**Comment by dattaz** [comment]
We should also to this for user

**Comment by dattaz** [comment]
q/[post_id] will link to question
u/[user_id] will link to user page
a/[post_id]#a[post_id] will link to answer
Done in merge_xml commit ba82e26

**Comment by amirouche** [comment]
Nice!

**Comment by dattaz** [comment]
Finally : 
question/[post_id].html will link to question
user/[user_id].html will link to user
answer/[post_id].html#a[post_id]
