### ISSUE TITLE
Create a --resume option

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#42]
I can not decide how this should work, but having to redownload everything/everytime seems to be a problem.

**Comment by dattaz** [comment]
You can use --directory= to specify dump dir. But i'll add a option to resume without re-construct prepare.xml

**Comment by dattaz** [comment]
In a normal run, script download dump, generate data, then zim and remove dump and data (only the zim file exists after running)
```--resume``` option can be useful when script has been stopped during this run.
We can't know where it has stop, what we can do it's just not restating from scratch and not re-downloading dump and not re-prepare dump.

this what you have in mind @kelson42 ?

**Comment by kelson42** [comment]
We have two kinds of data:
1 - What comes from archives.org: xml file in both compressed and uncompressed forms and the corresponding HTML
2 - The (optimised) images

Per default, it should test if each of the element of (1) exists and reuse it if possible. Otherwise do the necessary. If an option --reset is used then everything in (1) should be removed.

(2) should always be reused. If we really want to restart this, the option --reset-images should be used. All the optimised pictures should be put in a cache (one subdirectory per project) and linked (hard link) in the output directory (the one which is the base for the ZIM file).
