### ISSUE TITLE
Delete temporary data if restarting

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#43]
Currently the script complains about pre-existing data.

**Comment by dattaz** [comment]
When this append it complains at start.
This case only append when : 
- ```--nozim``` option has been pass to a previous run ; IMO user should explicitly delete these data from previous run
- Previous run that has crash, this shouldn't happen and it's a very specific case.

IMO no action is require, maybe a more informative message ?
What do you think ?

**Comment by kelson42** [comment]
I think if #42 is implemented  correctly, then this problem should be fixed too. I close it.
