### ISSUE TITLE
Can't install sotoki

### ISSUE THREAD

**Issue by okkebal** [openzim/sotoki#57]
Now that Sotoki is capable I'd like to give it a try. I followed the instructions (using Kubuntu). When I do

pip install sotoki

it says:

(.....)
    building 'lxml.etree' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    creating build/temp.linux-x86_64-2.7/src/lxml
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/libxml2 -I/tmp/pip-build-k5sato/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -lxslt -lexslt -lxml2 -lz -lm -o build/lib.linux-x86_64-2.7/lxml/etree.so
    /usr/bin/ld: cannot find -lz
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
  Can't rollback lxml, nothing uninstalled.
Command "/home/menno/venv/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-k5sato/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-N57HO6-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/menno/venv/include/site/python2.7/lxml" failed with error code 1 in /tmp/pip-build-k5sato/lxml/

**Comment by dattaz** [comment]
It's not sotoki but one of this dependances : lxml , it's seems one deps is missing, you should consulte this page i think http://lxml.de/installation.html

FYI : kiwix will (in a short term) provide zim file of stackexchange sites and stackoverflow

**Comment by kelson42** [comment]
Yes, it's already partly there http://download.kiwix.org/zim/stack_exchange/

**Comment by okkebal** [comment]
I've seen these zims wich is why I wanted to try to make a ZIM of parenting.stackexchange.com. I downloaded the big torrent dump, installed using the instructions here. 

Indeed lxml does not seem to want to install using this "pip" program.

It seems lxml 3.5.0 is installed. Does Sotoki use a different version?

I also noticed there are no indexes (portable versions) yet. I am generating these now. It takes forever for StackOverflow. I could share these indexes if you want?

**Comment by okkebal** [comment]
I managed to install Sotoki now. Indeed I needed to downgrade to lxml 3.4.4. wich dod not work becuase of some dependencies. 

https://stackoverflow.com/questions/6504810/how-to-install-lxml-on-ubuntu/6504860#6504860

**Comment by okkebal** [comment]
Great so now I need zimwriterfs, of wich no binaries are available. No easy way to install. I guess this is just too much for you average PHP programmer.   I think I'm gonna give up here

**Comment by okkebal** [comment]
Tying to Build openzim-master

In the instructions here: https://github.com/wikimedia/openzim/tree/master/zimwriterfs

cd ../zimlib && ./autogen.sh && ./configure && make && cd ../zimwriterfs

./autogen.sh: 8: ./autogen.sh: libtoolize: not found
./autogen.sh: 12: ./autogen.sh: aclocal: not found
./autogen.sh: 13: ./autogen.sh: autoheader: not found
./autogen.sh: 14: ./autogen.sh: autoconf: not found
./autogen.sh: 15: ./autogen.sh: automake: not found

You need to :
sudo apt-get install build-essential libtool
sudo apt-get install automake

Still not giving up...

**Comment by okkebal** [comment]
Seems like the "make" command worked. But now I cannot figure out where the binaries are or how to execute them or how to add them to my path sothat Sotoki can find them.

(If you did not guess I am pretty new to this)

**Comment by okkebal** [comment]
No Make file is not there you. I get an error abou 'xapian' so I did:

sudo apt-get install libxapian-dev

Now the error is:
error: xapian version must be >= 1.4.2

So I Do:
sudo apt-get install libxapian-dev=1.4.2-1

And I get:
E: Version '1.4.2-1' for 'libxapian-dev' was not found

**Comment by okkebal** [comment]
Even over at Debian Backports..  the latest version is 1.4.1

https://packages.debian.org/search?keywords=xapian&searchon=names&section=all&suite=jessie-backports

**Comment by okkebal** [comment]
So I managed to build from sources xapian 1.4.4 and xapian-bindings from the xapian website.

Now the ./configure command (to build zimwriterfs) works!

But make does this:

 make
/bin/bash ./libtool  --tag=CXX   --mode=link g++ --std=c++0x  -I/usr/local/include -Wall -I../zimlib/include  -O3 -L/usr/lib/x86_64-linux-gnu -licui18n -licuuc -licudata   -L/usr/local/lib -lxapian -L../zimlib/src/.libs -o zimwriterfs zimwriterfs-zimwriterfs.o zimwriterfs-tools.o zimwriterfs-article.o zimwriterfs-articlesource.o zimwriterfs-indexer.o zimwriterfs-resourceTools.o zimwriterfs-pathTools.o zimwriterfs-mimetypecounter.o zimwriterfs-xapianIndexer.o xapian/zimwriterfs-myhtmlparse.o xapian/zimwriterfs-htmlparse.o  -lgumbo -lpthread -lmagic -lz -lzim -llzma 
libtool: link: g++ --std=c++0x -I/usr/local/include -Wall -I../zimlib/include -O3 -o .libs/zimwriterfs zimwriterfs-zimwriterfs.o zimwriterfs-tools.o zimwriterfs-article.o zimwriterfs-articlesource.o zimwriterfs-indexer.o zimwriterfs-resourceTools.o zimwriterfs-pathTools.o zimwriterfs-mimetypecounter.o zimwriterfs-xapianIndexer.o xapian/zimwriterfs-myhtmlparse.o xapian/zimwriterfs-htmlparse.o  -L/usr/lib/x86_64-linux-gnu -licui18n -licuuc -licudata -L/usr/local/lib /usr/lib/x86_64-linux-gnu/libxapian.so -L../zimlib/src/.libs -lgumbo -lpthread -lmagic -lz /home/menno/openzim-master/zimlib/src/.libs/libzim.so -llzma
zimwriterfs-xapianIndexer.o: In function `XapianIndexer::XapianIndexer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)':
xapianIndexer.cpp:(.text+0x223a): undefined reference to `Xapian::TermGenerator::set_stopper_strategy(Xapian::TermGenerator::stop_strategy)'
zimwriterfs-xapianIndexer.o: In function `XapianIndexer::indexingPrelude(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
xapianIndexer.cpp:(.text+0x2a0c): undefined reference to `Xapian::WritableDatabase::WritableDatabase(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int)'
zimwriterfs-xapianIndexer.o: In function `XapianIndexer::indexingPostlude()':
xapianIndexer.cpp:(.text+0x82): undefined reference to `Xapian::Database::compact_(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, int, unsigned int, int, Xapian::Compactor*) const'
collect2: error: ld returned 1 exit status
Makefile:485: recipe for target 'zimwriterfs' failed
make: *** [zimwriterfs] Error 1

**Comment by okkebal** [comment]
It now has become a Xapian or Openzim issue. Well I wanted to make some Zim files and try to make the sotoki zims a bit nicer to look at. As a designer I can see the Html/css/JS but I can't get it to work.  I coult try again on osx or Windows but usually these things are easiest in Linux.

**Comment by dattaz** [comment]
I understand it's seems hard but, if you want there is a VM with already zimwriterfs and tools for zim available : http://download.kiwix.org/dev/ZIMmakerVMv6.ova
All dependances for zimwriterfs are available (in the good version) in debian but in the next release (stretch) which come at the end of the month.

We need help to make sotoki zim nicer, for exemple with that : https://github.com/openzim/sotoki/issues/53 so i hope you will not give up :)

i'll upload zim of parenting.stackexchange.com later today.

**Comment by okkebal** [comment]
Ah great a VM where everything just works. So how do I open that? Because I do not have a VMWare licence.

**Comment by dattaz** [comment]
virtualbox is ok

**Comment by okkebal** [comment]
I have the zimmaker VM running now, but what is the root password of this VM??

**Comment by dattaz** [comment]
Use sudo with "zimmaker" as password

**Comment by dattaz** [comment]
File is here for one week : https://framadrop.org/r/hduez3WnbK#5L/zKgOE6eY3eet1P5h9u4D6LOm4JdkMvHTg2+g1mEQ=

**Comment by okkebal** [comment]
Wow thanks so much, never heard of Framadrop its a bit like Freenet. I like it. A bit slow though, but thanks for the file. I am making indexes for all these Sotoki files. My computer is still at it trying to create one for StackOverflow..... its at 42%...  It will probably finish next week :) With these indexes the zim files are so much more usable. 

I did notice that StackOverflow starts giving suggestions once you type in ONE character (no index) Windows does not like that and hangs for about ten seconds before responding with useless one letter search results. It should start searching when 3 or more characters are entered. I don't know if this is ZIM specific or that this is something that needs to be fixed in the Zim client.

**Comment by okkebal** [comment]
I've got Sotoki running in the VM now. Its generating a ZIM file. It works! Thanks. But now I want to try to make changes to it. I tried "whereis sotoki" but nothing. Where can I find Sotoki now? I can see the sources here on Git but where are they on the computer when you have done "pip install sotoki"?

**Comment by okkebal** [comment]
Sotoki is a script right? no compiling? or is it an binary? I gueass my question is "how do I set up a development environment where I can make changes to the sources an then test it.

**Comment by kelson42** [comment]
BTW, there is also also the Sotoki Docker image which allow quickly to use Sotoki https://hub.docker.com/r/openzim/sotoki.

**Comment by dattaz** [comment]
Yep it's a script, you can clone this repo on your github account, make a new branch to work on, and then you can launch in sotoki/ by using python sotoki.py

**Comment by okkebal** [comment]
I did this:

git clone https://github.com/openzim/sotoki
cd sotoki
python sotoki.py

It now sais:

Traceback (most recent call last):
  File "sotoki.py", line 35, in <module>
    from subprocess32 import call
ImportError: No module named subprocess32

**Comment by kelson42** [comment]
@okkebal Follow the README https://github.com/openzim/sotoki/blob/master/README.md

**Comment by okkebal** [comment]
Ah oh, so I needed to start the virtual environment first like it said in the readme. Well I can finally make zim files and change code! Thanks so much.

**Comment by okkebal** [comment]
I've made changes to the design and index. It now shows only 100 tags on the index and the top 50 most popular questions. There now is an "all tags" page with this terrible big list of tags that used to be the index. I've created a new ZIM file for AI.stackexchange to test. Please take a look. 

http://www.zorgsite.nl/files/ai.stackexchange.com_en_all_2017-06.zim

I did 

git clone https://github.com/openzim/sotoki 

And made changes to the code, made some Zims etc. But I have no Idea how to get these changes back on the Git. I've tried to read the Git documentation but I just don't get it at all and my head hurts. Do I have to submit each file with a seperate command?  What command should I use to just upload all my changes? Wich GUI could I use for Git? I'll take another look tomorrow, but maybe you guys know some easy way to get this done?

Another question: wich HTML minifier should I use to create the minified versions of the template? Is there some special Jinja compressor, or can you use any (online) HTML minfier?

**Comment by dattaz** [comment]
Wow ! Really cool ! 👍👍
I'm not sure about the blue, but what you propose is definitely better than what we have.
3 remarks : 
 - color should take all the page (you have blank border at left and right)
 - "This (question|user page) is issued from XXX" is missing at the end of question page and user page
- "This website was generated by sotoki using stackexchange network database dump." is missing of index.html, alltags.html and tag pages

For the minifier i do it by the hand (maybe you can use minifier). templates, templates_mini and templates_mini_mathjax should we update. 

To submit patch you should normally made a pull request from your own repo.
1. Fork this repo to your github account (fork button on the top of the page)
2. Add your repo locally : `git remote rename origin upstream`
and `git remote add origin https://github.com/okkebal/sotoki` 
3. Made `git add` for each file you have modified (and you want to commit)
4. `git commit `
5. `git push -u origin master`
6. Go to your repo page : https://github.com/okkebal/sotoki and click to "pull request"

Normally you made 1 branch by feature/Pull request but i'm not so sure about how to made a branch after modification, but next time start with a new branch that you push to your repo and then pull request the branch.

PS : next time please open a new issue and/or pull request for discussion/submission of new idea

**Comment by okkebal** [comment]
- On very large monitors its prettier not to make the whole background one color. I added a shadow to make it a bit nicer.
- Yes I removed the sentence at the bottom. I thought it did not add much. Makes the Zim file bigger and only annoys me. 
- Same here: it is important to keep a copyright there, but why should each page say that is has been generated by Sotoki? What good is that to the user?

Hand minification involves removing enters??

I tried making the fork. Did it work?

**Comment by okkebal** [comment]
It looks like it worked. On the "pull requests" page I can see my changes. What am I supposed to do there?

**Comment by okkebal** [comment]
When I use minified HTML from templates_mini folder the ZIM file actually gets bigger by 1 mb.. 

??

**Comment by dattaz** [comment]
Yep agree with you: 
- "This (question|user page) is issued from XXX" should be here because legal and because it's had link to original content
- generated by sotoki can be only on index.html

Yep hand minification is just removing enters and useless space, we haven't made any benchmark on minification but, with the current status i made smaller zim with templates_mini than templates.

Your fork seems ok, on the pull requests you should follow this : https://help.github.com/articles/creating-a-pull-request/

**Comment by okkebal** [comment]
I put back the bottom lines as you suggested.

Ok, so I made a pull request. Hopefully It works.
