### ISSUE TITLE
Crash scenario

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#58]
```
$ sotoki 3dprinting.stackexchange.com Kiwix
Traceback (most recent call last):
  File "/media/kelson/SOTOKI/venv/bin/sotoki", line 11, in <module>
    sys.exit(run())
  File "/media/kelson/SOTOKI/venv/local/lib/python2.7/site-packages/sotoki/sotoki.py", line 998, in run
    parser.setContentHandler(UsersRender(templates, output, title, publisher, dump, cores, cursor, conn, deflate,url,redirect_file))
  File "/media/kelson/SOTOKI/venv/local/lib/python2.7/site-packages/sotoki/sotoki.py", line 393, in __init__
    os.makedirs(os.path.join(output, 'user'))
  File "/media/kelson/SOTOKI/venv/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: 'work/3dprinting_stackexchange_com/output/user'
```

FYI, the precedent run died because zimwriterfs was not able to start correctly. Might also make sense to check if zimwriterfs can be started correctly.

**Comment by dattaz** [comment]
What do you want to say by : "zimwriterfs was not able to start correctly" ?

Currently, when zimwriterfs crash, the generated files are left in place to just have to relanch zimwriterfs (which have it's command with arguments print). And if you want to re-start everything add : --clean-previous
Maybe it's not the good workflow?

**Comment by kelson42** [comment]
@dattaz 

It should not die, in worse case it should stops with a proper error. But the right behaviour should be to resume.

I'm not sure to remember exactly what mean these three options: [--reset] [--reset-images] [--clean-previous]. Would be great to have a bit more details about each option in the usage (one line with explanaition by option).

**Comment by dattaz** [comment]
I have add a message with some explanation (and after this message programme stop) 
Also options are now print by default (previously -h)
