### ISSUE TITLE
Improve user support

### ISSUE THREAD

**Issue by amirouche** [openzim/sotoki#6]
- [x] create user page
- [x] add identicon (https://github.com/azaghal/pydenticon)
- [x] add badges to users in user page and question page
- [x] fix user link page in question page
- [ ] add user questions and answers
- [x] use user profile image when available

**Comment by kelson42** [comment]
+++

**Comment by dattaz** [comment]
I haven't add  "user questions and answers" because of the way we handle dump it's will need lot of more work (not to write code for that but at run time). I don't think it's really useful.
If you think it's really important, feel free to re-open to discuss
