### ISSUE TITLE
sotoki zims dont work on Android

### ISSUE THREAD

**Issue by okkebal** [openzim/sotoki#61]
I tried to open ai.stackexchange zim on my android 6 phone, first page loads ok, but question pages all pictures and css files are broken. It does work on kiwix serve and kiwix for Windows.  This problem is not caused by my changes. I tried with the original Zim from download.kiwix

**Comment by dattaz** [comment]
see https://github.com/kiwix/kiwix-android/issues/69

**Comment by kelson42** [comment]
https://github.com/kiwix/kiwix-lib/issues/70
