### ISSUE TITLE
Mathjax is ok on serveur but not on kiwix desktop

### ISSUE THREAD

**Issue by dattaz** [openzim/sotoki#63]
Open "Can one latexify formulae on Signal Processing meta?" of "meta.dsp.stackexchange.com_en_all_2017-06.zim" 
Check first answers on desktop and on a web browser (using server)
It's not a problem of a ressource that is load from internet

**Comment by dattaz** [comment]
Same with kiwix for android

**Comment by okkebal** [comment]
You have a patch for this right?

**Comment by dattaz** [comment]
nop, it's seems a issue on kiwix for android/kiwix desktop

**Comment by okkebal** [comment]
It has nothing to do with my changes?

**Comment by dattaz** [comment]
No, was here before (i have check)

**Comment by okkebal** [comment]
It probably has to do with the rendering engine (Gecko)
Upgrading XULRunner probably does the trick. The latest version is based on Firefox 45, so you should see if MathJax works in FF 45. If it does then it will probably also run in XULrunner 45.

**Comment by kelson42** [comment]
@okkebal I agree. We should focus on getting this working on Android/iOS first.

**Comment by kelson42** [comment]
I think we should close the issue here as this is not a problem with Sotoki. We are working on kiwix-destkop 2.0 which first versions will be released in the next months. I will take care that mathjax works properly.
