### ISSUE TITLE
Many ZIM file have CSS problems

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#64]
Recently done ZIM files might (not all of them) have problem with CSS:
* http://download.kiwix.org:8080/matheducators.stackexchange.com_en_all_2017-06/
* http://download.kiwix.org:8080/mathematica.stackexchange.com_en_all_2017-06/
* http://download.kiwix.org:8080/mathoverflow.net_en_all_2017-06/

But other ones no:
* http://download.kiwix.org:8080/martialarts.stackexchange.com_en_all_2017-06/

**Comment by dattaz** [comment]
The cause is a mistake with mathjax templates in 0.7 version.
This is correct in the new version (0.8) release today

**Comment by okkebal** [comment]
So who is rendering the download.kiwix.org ZIM files? I see outdated SE files appearing there. Please use the new Sotoki to render them!

**Comment by kelson42** [comment]
@okkebal Yes, they have been rendered partly before the fixes. A new run will be done in June. I think we can clause that ticket.
