### ISSUE TITLE
HTTP 500 errors by running sotoki

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#65]
This seems to be new

$ sotoki 3dprinting.stackexchange.com Kiwix --clean-previous
remove work/3dprinting_stackexchange_com/output/user
remove work/3dprinting_stackexchange_com/se-dump.db
remove work/3dprinting_stackexchange_com/redirection.csv
Already 1000 Users done !
HTTP Error 500: Internal Server Error
Already 2000 Users done !
HTTP Error 500: Internal Server Error

**Comment by dattaz** [comment]
it's not new, sotoki print HTTP error when an (image) download fail.
because of  `--clean-previous` you clear image cache, so he re-download user image and some got a 500 error. In this case we fallback by generating one.

**Comment by dattaz** [comment]
Some user have on there user profile an image, so we try to download it. 
If download fail, we show error, like `HTTP Error 500: Internal Server Error` and we can't save a file we don't have.
So when you re-run, the file is still not here, so its try a new time to download it and show a new time error.
