### ISSUE TITLE
Sotoki will not install or build from pip on Arch Linux: "Command "python setup.py egg_info" failed with error code 1"

### ISSUE THREAD

**Issue by PharmaceuticalCobweb** [openzim/sotoki#70]
Followed the install instructions in the README. Tried to satisfy all dependencies.

**Dependencies**:
jpegoptim: https://www.archlinux.org/packages/community/x86_64/jpegoptim/
pngquant: https://aur.archlinux.org/packages/pngquant/
gifsicle: https://www.archlinux.org/packages/extra/x86_64/gifsicle/
advancecomp: https://aur.archlinux.org/packages/advancecomp/ or https://aur.archlinux.org/packages/advancecomp-git/
python-pip: https://www.archlinux.org/packages/extra/any/python-pip/
python-virtualenv: https://www.archlinux.org/packages/extra/any/python-virtualenv/
python-dev: Not needed ( https://bbs.archlinux.org/viewtopic.php?id=39935#p299628 )
libxml2-dev: https://www.archlinux.org/packages/extra/x86_64/libxml2/
libxslt1: Couldn't find this one?
libbz2-dev: https://www.archlinux.org/packages/core/x86_64/bzip2/
p7zip-full: https://www.archlinux.org/packages/extra/x86_64/p7zip/
python-pillow: https://www.archlinux.org/packages/community/x86_64/python-pillow/
gif2apng: https://aur.archlinux.org/packages/apng-utils/
imagemagick: https://www.archlinux.org/packages/extra/x86_64/imagemagick/

**Steps to reproduce**:
1. Install the above packages on an up-to-date Arch Linux or Parabola GNU/Linux-libre install (tired on both).
2. Run "virtualenv --system-site-packages venv".
3. Run "source venv/bin/activate".
4. Run "pip install sotoki" or "pip install git+git://github.com/openzim/sotoki.git". Expected output: pip installs sotoki without error. 

**Current output for "pip install sotoki"**:
```
Collecting sotoki
  Using cached sotoki-0.8.3.tar.gz
Collecting Jinja2==2.8 (from sotoki)
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting lxml==3.4.4 (from sotoki)
  Using cached lxml-3.4.4.tar.gz
Collecting MarkupSafe==0.23 (from sotoki)
  Using cached MarkupSafe-0.23.tar.gz
Requirement already satisfied: docopt==0.6.2 in /usr/lib/python3.6/site-packages (from sotoki)
Collecting slugify==0.0.1 (from sotoki)
  Using cached slugify-0.0.1.tar.gz
Collecting pydenticon==0.2 (from sotoki)
  Using cached pydenticon-0.2.tar.gz
Collecting bs4 (from sotoki)
  Using cached bs4-0.0.1.tar.gz
Collecting envoy (from sotoki)
  Using cached envoy-0.0.3-py2.py3-none-any.whl
Collecting subprocess32 (from sotoki)
  Using cached subprocess32-3.2.7.tar.gz
    Complete output from command python setup.py egg_info:
    This backport is for Python 2.x only.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-m55ykqnm/subprocess32/
```

**Current output for "pip install git+git://github.com/openzim/sotoki.git"**:

```
Collecting git+git://github.com/openzim/sotoki.git
  Cloning git://github.com/openzim/sotoki.git to /tmp/pip-u8p76x_o-build
Collecting Jinja2==2.8 (from sotoki==0.8.3)
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting lxml==3.4.4 (from sotoki==0.8.3)
  Using cached lxml-3.4.4.tar.gz
Collecting MarkupSafe==0.23 (from sotoki==0.8.3)
  Using cached MarkupSafe-0.23.tar.gz
Requirement already satisfied: docopt==0.6.2 in /usr/lib/python3.6/site-packages (from sotoki==0.8.3)
Collecting slugify==0.0.1 (from sotoki==0.8.3)
  Using cached slugify-0.0.1.tar.gz
Collecting pydenticon==0.2 (from sotoki==0.8.3)
  Using cached pydenticon-0.2.tar.gz
Collecting bs4 (from sotoki==0.8.3)
  Using cached bs4-0.0.1.tar.gz
Collecting envoy (from sotoki==0.8.3)
  Using cached envoy-0.0.3-py2.py3-none-any.whl
Collecting subprocess32 (from sotoki==0.8.3)
  Using cached subprocess32-3.2.7.tar.gz
    Complete output from command python setup.py egg_info:
    This backport is for Python 2.x only.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6lo5ptnc/subprocess32/
```

:( I'd like update my stackexchange zim's to the new style, most of the ones on Kiwix's site are using the old style.

**Comment by kelson42** [comment]
@PharmaceuticalCobweb Thank you for the issue, which SE ZIM file are you interested in particular? I'm currently rebuilding all of them (stackoverflow currently building)

**Comment by PharmaceuticalCobweb** [comment]
I'm using quite a few of them since I'm often without an Internet connection. Not all of them are on the Kiwix site right now (still don't understand why unix.stackexchange.com isn't on Kiwix's site, it's the main one I'd like). 

Top 3:
1. Unix
2. SuperUser
3. StackOverflow

Full list:
AskUbuntu
Blender
Cryptography
ElementaryOS
NetworkEngineering
Photography
Puzzling
RetroComputing
ReverseEngineering
ServerFault
Skeptics
Space
StackOverflow
SuperUser
Tex
Tor
Travel
Unix

**Comment by dattaz** [comment]
About the issue, it seems to be subproccess32's fault, maybe try to install https://www.archlinux.org/packages/community/x86_64/python2-subprocess32/

**Comment by PharmaceuticalCobweb** [comment]
> About the issue, it seems to be subproccess32's fault, maybe try to install https://www.archlinux.org/packages/community/x86_64/python2-subprocess32/

Doesn't seem to have worked, though I didn't have it installed. Installed it got the same error:

```
[user@hostname]$ pip install git+git://github.com/openzim/sotoki.git
Collecting git+git://github.com/openzim/sotoki.git
  Cloning git://github.com/openzim/sotoki.git to /tmp/pip-3uny5eh6-build
Collecting Jinja2==2.8 (from sotoki==0.8.3)
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting lxml==3.4.4 (from sotoki==0.8.3)
  Using cached lxml-3.4.4.tar.gz
Collecting MarkupSafe==0.23 (from sotoki==0.8.3)
  Using cached MarkupSafe-0.23.tar.gz
Requirement already satisfied: docopt==0.6.2 in /usr/lib/python3.6/site-packages (from sotoki==0.8.3)
Collecting slugify==0.0.1 (from sotoki==0.8.3)
  Using cached slugify-0.0.1.tar.gz
Collecting pydenticon==0.2 (from sotoki==0.8.3)
  Using cached pydenticon-0.2.tar.gz
Collecting bs4 (from sotoki==0.8.3)
  Using cached bs4-0.0.1.tar.gz
Collecting envoy (from sotoki==0.8.3)
  Using cached envoy-0.0.3-py2.py3-none-any.whl
Collecting subprocess32 (from sotoki==0.8.3)
  Using cached subprocess32-3.2.7.tar.gz
    Complete output from command python setup.py egg_info:
    This backport is for Python 2.x only.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-72e0zhqz/subprocess32/
```

**Comment by kelson42** [comment]
I'm not an expert, but this sounds more to be a problem with the "subprocess32" module than with sotoki?! Maybe the bug should be reported there?

Otherwise you might also give a try to our Docker image:
https://hub.docker.com/r/openzim/sotoki/

**Comment by kelson42** [comment]
@PharmaceuticalCobweb I close this ticket as it seems quite clear that there is nothing we can do on our side.
