### ISSUE TITLE
Make nopic versions

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#74]
_From @amirh123123 on March 17, 2018 10:26_

hi please make stack_exchange all nopic thanks

_Copied from original issue: openzim/mwoffliner#248_

**Comment by dattaz** [comment]
do we automatically make a nopic version each time (in addition to zim with pictures) or is it an option?

**Comment by amirh123123** [comment]
example wordpress.stackexchange.com_en_all_2018-04.zim have nany pictures but i want make wordpress.stackexchange.com_en_nopic_2018-04.zim dont have pictures just text

**Comment by dattaz** [comment]
This will work in the next release

**Comment by kelson42** [comment]
@dattaz Thx for implementing this. You mean `--nopic` I suppose?

**Comment by dattaz** [comment]
Yes, `--nopic` sorry :(
