### ISSUE TITLE
User profiles pollute the article namespace

### ISSUE THREAD

**Issue by Jaifroid** [openzim/sotoki#77]
We develop Kiwix JS, a JavaScript-based ZIM file reader. The reader has a random button which offers a randomly selected article for the user to read. However, because on Stackexchange ZIMs there are a lot of user profiles in proportion to articles, nearly half the time the randomization routine returns a user profile.

While we could work around this in the reader, it has been suggested by @kelson42 that this issue is better fixed in the ZIM production process than in the reader. An issue here is that user profiles are appearing in the A/ namespace, which should be reserved for Articles according to the ZIM File spec. It is also the case that Tags are polluting the A/ namespace, whereas the spec seems to suggest that U/ or V/ should be used for categories.

Is there any way in which user profiles, which are of little interest to someone using a Stackexchange ZIM as a source of information, could be placed in a different namespace, so that we can guarantee that only Articles (i.e. Questions and Answers in the context of Stackexchange) appear in the A/ namespace?

**Comment by dattaz** [comment]
This seems impossible, since zimwriterfs (tool we use to build zim) does not support this, and @kelson42 say me "we never implemented properly that part of the spec"

I'm totally agree that it's not something we want to have in random selection, but these page are part of the website ("who has wrote this comment/question ?").

**Comment by Jaifroid** [comment]
OK, thanks @dattaz . So maybe we need to work around it in readers for now. What would you advise, @kelson42 ?

**Comment by kelson42** [comment]
@dattaz Would that be complicated to provide an option to avoid scrapping the profiles? I'm not really sure about the added value.

**Comment by dattaz** [comment]
No, it's doesn't seems complicated

**Comment by kelson42** [comment]
@dattaz Seems to me the best workaround to just remove them - but we need to be sure no link point to them (anymore).

**Comment by dattaz** [comment]
We now have option `--no-userprofile`

**Comment by Jaifroid** [comment]
Thank you, @dattaz . I was also thinking that this might be a wise move given GPDR. Although users may be deemed to have accepted publication of information about their alias on Stackexchange, do we want to deal with the question of whether they have given permission for that information to be "republished" in a ZIM archive that may persist indefinitely and that they cannot easily edit? Maybe this is marginal for GPDR, but it seems like a potential complication of including user profiles in ZIMs.
