### ISSUE TITLE
zimwriterfs complains of lot of invalid redirection

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#78]
Here is (a small part of) the log
```
remove invalid redirection user/3888706/user3888706.html redirecting to (missing) user/3888706/user3888706.html
remove invalid redirection user/3888707/andrey-belkin.html redirecting to (missing) user/3888707/andrey-belkin.html
remove invalid redirection user/3888709/user3888709.html redirecting to (missing) user/3888709/user3888709.html
remove invalid redirection user/3888710/lsutiger2015.html redirecting to (missing) user/3888710/lsutiger2015.html
remove invalid redirection user/3888711/opeshm.html redirecting to (missing) user/3888711/opeshm.html
remove invalid redirection user/3888712/bryan-napat-guinto.html redirecting to (missing) user/3888712/bryan-napat-guinto.html
remove invalid redirection user/3888713/user3888713.html redirecting to (missing) user/3888713/user3888713.html
remove invalid redirection user/3888714/s-mas.html redirecting to (missing) user/3888714/s-mas.html
remove invalid redirection user/3888715/olgun.html redirecting to (missing) user/3888715/olgun.html
remove invalid redirection user/3888717/adela-ruffatti.html redirecting to (missing) user/3888717/adela-ruffatti.html
remove invalid redirection user/3888718/ameer-hamza.html redirecting to (missing) user/3888718/ameer-hamza.html
remove invalid redirection user/3888719/delgadom.html redirecting to (missing) user/3888719/delgadom.html
remove invalid redirection user/3888720/user3888720.html redirecting to (missing) user/3888720/user3888720.html
remove invalid redirection user/3888721/user3888721.html redirecting to (missing) user/3888721/user3888721.html
remove invalid redirection user/3888722/user3888722.html redirecting to (missing) user/3888722/user3888722.html
remove invalid redirection user/3888723/user3888723.html redirecting to (missing) user/3888723/user3888723.html
remove invalid redirection user/3888724/aloe.html redirecting to (missing) user/3888724/aloe.html
remove invalid redirection user/3888725/sanvir.html redirecting to (missing) user/3888725/sanvir.html
remove invalid redirection user/3888726/freeze.html redirecting to (missing) user/3888726/freeze.html
remove invalid redirection user/3888727/casey-ferguson.html redirecting to (missing) user/3888727/casey-ferguson.html
remove invalid redirection user/3888728/erik.html redirecting to (missing) user/3888728/erik.html
```

**Comment by dattaz** [comment]
What surprising is the redirection redirect to same path. It's seems really strange for me to have this...(I just check the code, for the moment i do not understand how we can have this result....)
Can you send me redirect.csv ? I haven't them in the redirect.csv you provide me month ago.

Users with this problem seems to follow in user id, is this the same problem with all users?

**Comment by kelson42** [comment]
@dattaz Here it is http://tmp.kiwix.org/redirection.csv

**Comment by dattaz** [comment]
We have issue in libzim, it's harder to debug.....anyway, a just check `redirection.csv`, in this file path are ok.
So the problem is some files for any reasons are not write/not write at good place, can you also provide me a list of path, with `find [work/stackoverflow_com or something like that]  -type f > path_stackoverflow_13_06_18`. Thanks

**Comment by kelson42** [comment]
@dattaz Please open a ticket on libzim side, I have no time in the next 4 days to handle that, but @mgautierfr might.

**Comment by dattaz** [comment]
I just try to reproduce, i extract these user from stackoverflow dump, and put them in a smaller dump, no issue.I'll try with all user
I also have try superuser.com,which is one of biggest stackexchange site, I haven't got any issue with redirection like this one. (but i found 3 mirror that i've fix)

**Comment by dattaz** [comment]
I just generated all user from stackoverflow and I still not reproduce (all path in redirection.csv are present in file system...) :thinking:

**Comment by kelson42** [comment]
@dattaz So the problem is that someone the zimwriterfs does not do what it should.? The redirection file is OK?

**Comment by kelson42** [comment]
@dattaz OK, the error msg is wrong in the log, the targeted url is always the same as the source. Should be ok in next nightly.

**Comment by dattaz** [comment]
@kelson42 yes apparently something wrong, i think with zimwriterfs, with information that i have. But i'll be sure if you can provide me working tree (`find [work/stackoverflow_com or something like that] -type f > path_stackoverflow_13_06_18`) to check if files are really present, thanks

**Comment by dattaz** [comment]
Bug is on sotoki side, only 3 226 079 users profiles are produce (normally ~8 500 000)

**Comment by kelson42** [comment]
Seems to work now, but the one I have generated was "without profiles"... so not sure the bug is fixed. But let consider it is the case.
