### ISSUE TITLE
Does is make sense to mirror all "meta" web sites

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#82]
@dattaz What is their content? It seems that each forum has its meta counterpart. Does that really make sense to you?

**Comment by dattaz** [comment]
For their content see : [What is meta](https://meta.stackexchange.com/help/whats-meta)
For me no, there is no sense

**Comment by kelson42** [comment]
@dattaz Agree, should we modify list_all.sh to remove them?

**Comment by kelson42** [comment]
Fixed
