### ISSUE TITLE
Use in-memory image optimizer

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#84]
The current solution generates a lot of IO by writting, reading and re-writting images on the fs for optimisation.

**Comment by HAKSOAT** [comment]
Hello @kelson42 could you help with pointers regarding this issue? I currently do not know what `fs` means, neither do I know where the current solution lies in the code base.

**Comment by kelson42** [comment]
« Fs » means filesystem. I don’t have code Sotoki, but part of it recomputes all images with tools like jpegoptim or pngquant... they all write temporary things to the fs which is slow.... we should find a better solution by writing to /dev/shm for example or use in-memory optimization.

**Comment by HAKSOAT** [comment]
Okay. Thanks.
