### ISSUE TITLE
Problem with C# tag link on the homepage

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#86]
Tested with `stackoverflow.com_en_all_2019-02.zim` the link the not open the proper page. The reason is that it is `../I/tag/c%23/1.html` and it should be `../A/tag/c%23/1.html`.

First reported at https://github.com/kiwix/kiwix-js/issues/359

**Comment by adrian-azad** [comment]
i'll check that when i find some time to investigate, but it's seems more a zimwriterfs issue no ? (wrong namespace)

**Comment by dattaz** [comment]
I'll check that when i find some time, but seems more a zimwriterfs issue no ? (wrong namespace)

**Comment by kelson42** [comment]
@dattaz thx, you might be right even if I wonder about this could go wrong.

**Comment by rgaudin** [comment]
Looks like the `#` is interpreted as the _hash_ separator of the URL so zimwriterfs considers the leaf to be `/c` and does not recognize it as being part of the `/A` or `/-` namespaces (has this is based on extension), hence defaulting to `/I`.

Closing this and opening a specific one on zimwriterfs.
