### ISSUE TITLE
Use new tagging system

### ISSUE THREAD

**Issue by rgaudin** [openzim/sotoki#87]
In order to update ZIM files to the [new tagging system](https://wiki.openzim.org/wiki/Tags), please make sure your scraper:

* is using the lastest zimwriterfs (`1.3.5+` or `:latest` docker image). It supports new options and fixes important metadata (tags, favicon) and LZMA compression level.
* is including a `_category:xxx` tag (See [kiwix-tools#317](https://github.com/kiwix/kiwix-tools/issues/317))
* is including a tag for your content (ex: `Wikipédia`, `DirtyBiology`, etc.)
* is setting a proper `--name`.
* is using a proper `--flavour` (if relevant)
* is setting a `--scraper`.

**Comment by kelson42** [comment]
@dattaz Do you think you could help here?

**Comment by dattaz** [comment]
Yes i think i can do it next week.

Note : https://openzim.org/wiki/Metadata

**Comment by kelson42** [comment]
@dattaz Thank you! We are a bit moving on with all the scrapers in Python. Introducing one by one to the new Zimfarm system first, but also making a new maintenance round to help to fix the few pending bugs, improving the codefactor note, even introducing CI with automated tests and Travis CI. So, a bit of work to do :]
