### ISSUE TITLE
Script seems stuck after downloading, a warning message would be welcome

### ISSUE THREAD

**Issue by andre-paulo98** [openzim/sotoki#91]
I'm running this on Ubuntu on Windows 10 (the simple one you get from the Store)
I ran the command like: `sotoki stackoverflow.com Kiwix --threads=12 --reset --clean-previous --no-userprofile`

After a long time, after finishing the download for stackoverflow.com-Users.7z it just got stuck
```
stackoverflow.com-Users.7z: OK
Ok we have get dump

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=C.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (306C3),ASM,AES-NI)

Scanning the drive for archives:
1 file, 500347335 bytes (478 MiB)

Extracting archive: stackoverflow.com-Users.7z
--
Path = stackoverflow.com-Users.7z
Type = 7z
Physical Size = 500347335
Headers Size = 122
Method = BZip2
Solid = -
Blocks = 1

Everything is Ok

Size:       3526828401
Compressed: 500347335
/mnt/d/stackoveflow/work/stackoverflow_com /mnt/d/stackoveflow
 ```
And it's just stuck on that. I can't find a zim file, the execution is not over, should I keep waiting? It's been around 4 hours since that last line.

Thank you.

**Comment by andre-paulo98** [comment]
Its been around 8 hours since the last line. Is it still doing anything? Can I somehow stop and continue with the script (without having to download everything again)?

**Comment by andre-paulo98** [comment]
It finally started doing something.
The script is doing something with images.
Maybe a warning should be added before this part of the processing that it might take a long time for the next step would be usefull.

**Comment by kelson42** [comment]
@andre-paulo98 Would you be able to propose a PR?

**Comment by andre-paulo98** [comment]
I would do a PR, but my Python knowledge is very close to 0

**Comment by dattaz** [comment]
it decompresses a large file, it may take time.
You can add a message just before this line: https://github.com/openzim/sotoki/blob/master/sotoki/sotoki.py#L890
