### ISSUE TITLE
Move from Python2 (and abandon it) to Python3

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#92]
Looks like Sotoki is in Python2, it should be moved to Python3.

**Comment by dattaz** [comment]
Most of the work can be done with `2to3` (https://docs.python.org/3.9/library/2to3.html) but require to take time to check everything work correctly after that (or introduce test :smiley_cat:  )

**Comment by kelson42** [comment]
@dattaz If you fix it, I'm volunteer to test it.

**Comment by amirouche** [comment]
Do we want to support both Python 2 and Python3?

I vote for python 3 only support.

**Comment by kelson42** [comment]
@amirouche Python3 support only.

**Comment by dattaz** [comment]
First try with 2to3 is done on `to_python3` branch.
Still need debug.

**Comment by kelson42** [comment]
Done
