### ISSUE TITLE
Redirection format for zimwriterfs?

### ISSUE THREAD

**Issue by dattaz** [openzim/sotoki#95]
Using docker `openzim/zimwriterfs:latest`, `zimwriterfs` seems to not understand redirection file.
Exemple in redirection file :
```
A       question/999/napisannia-initsialiv-razom-chi-okremo.html        Question 999    question/999.html
```

Log from zimwriterfs  :
```
Invalid redirection A/question/999/napisannia-initsialiv-razom-chi-okremo.html redirecting to (missing) q/estion/999.html
```

**Comment by kelson42** [comment]
@dattaz I had a look and this looks like a serious bug in zimwriterfs. What are the step to reproduce it (sotoki command)?

**Comment by rgaudin** [comment]
Could fix it but am not sure where the fix should actually be placed. will sort that out with @kelson42

**Comment by dattaz** [comment]
>  What are the step to reproduce it (sotoki command)?
Just run sotoki.

Exemple : `sotoki 3dprinting.meta.stackexchange.com Kiwix --threads=1 --reset --clean-previous --no-userprofile --nopic`
which will call zimwriterfs like that : 
```
zimwriterfs --flavour="nopic" --withFullTextIndex  --inflateHtml --redirects="work/3dprinting_meta_stackexchange_com/redirection.csv" --welcome="index.html" --favicon="favicon.png" --language="eng" --title="3D Printing Meta Stack Exchange" --description="Q&A about the site for 3D printing enthusiasts" --creator="3D Printing Meta Stack Exchange" --publisher="Kiwix" --tags="_category:stack_exchange;stackexchange;nopic" --name="kiwix.3dprinting.meta.stackexchange.com.nopic" --scraper="sotoki 1.0" --source="https://3dprinting.meta.stackexchange.com" "work/3dprinting_meta_stackexchange_com/output" "work/3dprinting.meta.stackexchange.com_en_all_2020-02_nopic.zim"
```

Attached : redirection.csv 
[redirections.csv](https://github.com/openzim/sotoki/files/4270766/redirections.txt)


```
# zimwriterfs --version
Version:  v1.3.8
```

**Comment by rgaudin** [comment]
@dattaz, I already mentioned I found the root cause and assigned myself… Need to check with @kelson42 what is the expected behavior to place the fix in either zimwriterfs (most probably), libzim or sotoki.

**Comment by rgaudin** [comment]
@dattaz, here's the issue openzim/libzim/issues/298
