### ISSUE TITLE
Question links are wrong in ru.stackoverflow.rom_ru_all.zim

### ISSUE THREAD

**Issue by tigran123** [openzim/sotoki#97]
Downloaded the 3GB file http://download.kiwix.org/zim/ru.stackoverflow.com_ru_all.zim (MD5 c84b59672a50f9f1cb43bc9b1c49ff96) and opened in Chrome browser (running kiwix-serve on the server). But clicking on any of the questions results in an error like this:

```
Not Found
The requested URL "/ru.stackoverflow.com_ru_all/A/question/1811/hello-world-main.html" was not found on this server.

```

I tried searching and it gives the list of search results, but clicking on any of the items results in the same error as above.

Then I decided to test it with the Kiwix desktop application (on Linux of course) and there is the same problem, only I don't get an error message --- just an empty tab --- when I click on any of the question links.

**Comment by kelson42** [comment]
@tigran123 Thank you for this new bug report. I confirm the problem. It seems that all the articles are there. The article your search is available at http://library.kiwix.org/ru.stackoverflow.com_ru_all/A/question/1811.html. The problem is that the link in the home page is wrong for some kind of reason!

**Comment by kelson42** [comment]
@dattaz Would you be able to have a look to that one as well?

**Comment by dattaz** [comment]
This is maybe related to #95 ...
I'll take a look..

**Comment by kelson42** [comment]
@rgaudin @dattaz Do you think we can close that one?

**Comment by rgaudin** [comment]
It could not work without #95 being fixed. Just confirmed (on a smaller ZIM) that this is fixed as well.

**Comment by kelson42** [comment]
Definitly fixed in last version of the ZIM file https://download.kiwix.org/zim/stack_exchange/ru.stackoverflow.com_ru_all_2020-03.zim
